spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: ksh0558@

    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  mail:
    host: smtp.naver.com
    port: 465
    username: htw6269
    password: ha1102
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          ssl:
            enable: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000